#reviews_csv_path = "../data/reviews/single_record.csv"
#reviews_csv_path = "../data/reviews/iPadReviews_short.csv"
reviews_csv_path = "../data/reviews/iPadReviews.csv"
#reviews_csv_path = "../data/reviews/iPadManualTag.csv"
#reviews_csv_path = "../data/reviews/canont3iReviews.csv"